### ISSUE TITLE
CDI on EL-API dependency

### ISSUE THREAD

**Issue by Emily-Jiang** [jakartaee/cdi#426]
The [issue](https://github.com/eclipse/microprofile/issues/56) in MicroProfile was reported for a potential security vulnerability. Please comment if you disagree with the security vulnerability claim.

I noticed the el-api dependency was optional in CDI 1.0, but from CDI 1.1, the EL-API dependency is mandatory. Can someone explain why? Is it possible to make the dependency optional?

**Comment by manovotn** [comment]
I haven't known the spec long enough to answer why it was optional before and mandatory later on.
However, I think you cannot take it out now and claim backward compatibility. At least not in the full EE profile, anyway. Besides, if I recall correctly, all MP specs should exclude EL dep anyway?

**Comment by kenfinnigan** [comment]
It wasn't purely for security concerns, but also because in a microservice world you wouldn't be using JSF, which I believe is where the EL requirement comes from

**Comment by starksm64** [comment]
For CDI Lite the EL dependency is again removed.

**Comment by manovotn** [comment]
Closing this issue in favor of https://github.com/jakartaee/cdi/issues/613 where we already discuss a very similar topic.
