### ISSUE TITLE
Rework portable extension

### ISSUE THREAD

**Issue by Emily-Jiang** [jakartaee/cdi#434]
Rework portable extension so that they can be found at build time instead of runtime.

As a developer, I want to use cdi extension to:

- Providing its own beans, interceptors and decorators to the container

- Injecting dependencies into its own objects using the dependency injection service

- Providing a context implementation for a custom scope

- Augmenting or overriding the annotation-based metadata with metadata from some other source

**Comment by manovotn** [comment]
This issue is not outdated/resolved by having build compatible extensions, closing it.
