### ISSUE TITLE
Fix outdated info on the website and the cdi-spec github org

### ISSUE THREAD

**Issue by mkouba** [jakartaee/cdi#441]
* The website does not mention the new spec repo but mentions JIRA to track issues (https://issues.jboss.org/browse/CDI)
* The https://github.com/cdi-spec org does not mention the new spec repo

I'm aware of the fact that it's still work in progress but it wouldn't hurt to update at least some key parts.

**Comment by mkouba** [comment]
CC @antoinesd @starksm64

**Comment by antoinesd** [comment]
You're right @mkouba, I'll fix that after having my ruby and awestruct env fixed :-D

**Comment by manovotn** [comment]
The repo is now unused for a long period of time, I think we can close this issue as outdated. Feel free to reopen if you think otherwise.
