### ISSUE TITLE
How can getReference() legally be invoked during AfterDeploymentValidation event if contexts have not been created yet?

### ISSUE THREAD

**Issue by ljnelson** [jakartaee/cdi#454]
[Section 11.5.4](https://jakarta.ee/specifications/cdi/3.0/jakarta-cdi-spec-3.0.html#after_deployment_validation) says:

> The container must fire an event after it has validated that there are no deployment problems and **before creating contexts** or processing requests [emphasis mine].

[Section 11.3](https://jakarta.ee/specifications/cdi/3.0/jakarta-cdi-spec-3.0.html#beanmanager) indicates that it is legal to call [`BeanManager#getReference(Bean, Type, CreationalContext)`](https://jakarta.ee/specifications/cdi/3.0/apidocs/jakarta/enterprise/inject/spi/BeanManager.html#getReference-jakarta.enterprise.inject.spi.Bean-java.lang.reflect.Type-jakarta.enterprise.context.spi.CreationalContext-) in an `AfterDeploymentValidation` observer method.

In order to get contextual references, such as those returned by `getReference()`, you need a context.

Is this a bug in the specification?  Does section 11.5.4 need to be amended in some way?

**Comment by mkouba** [comment]
Well, the fact that  the `AfterDeploymentValidation` event must be fired **before** the contexts are created does not imply that the contexts must be created **after** all `AfterDeploymentValidation` observers are notified. For example, a context could be created/initialized lazily, once needed, therefore when calling `BeanManager#getReference()` **inside** an `AfterDeploymentValidation` observer method.

However, I think that the wording in section 11.3. could be relaxed a bit - I don't think the "before creating contex" part makes sense.

**Comment by manovotn** [comment]
So, the bean validation actually happens *before* your `AfterDeploymentValidation` listeners get notified. This fulfills what `Section 11.5.4` says and after that, you are free to create new beans (as per `Section 11.3`) inside that listener. The specification puts no restrictions on whether contexts need to be created eagerly or lazily.

You can take a look at how Weld does it [here](https://github.com/weld/core/blob/master/impl/src/main/java/org/jboss/weld/bootstrap/WeldStartup.java#L489-L522) - it shows the flow I just described.

> However, I think that the wording in section 11.3. could be relaxed a bit - I don't think the "before creating contex" part makes sense.

I agree it's not overly useful, but it is probably the only point which implies the earliest point at which contexts *can be* created?

**Comment by ljnelson** [comment]
> However, I think that the wording in section 11.3. could be relaxed a bit - I don't think the "before creating contex" part makes sense.

I agree.  If I remember my history right, there was a time when `getReference()` _was_ forbidden in here somewhere, and then those restrictions were relaxed.  The language looks like it just got left over.  Clearly you _can_ call `getReference()`, which means that contexts must be available (lazy or no) so we should probably just lose this language.

**Comment by manovotn** [comment]
>  If I remember my history right, there was a time when getReference() was forbidden in here somewhere

Well that's still there (11.3.), spec says that if you call `BM.getReference()` prior to ABV, you get an exception.

**Comment by ljnelson** [comment]
> > If I remember my history right, there was a time when getReference() was forbidden in here somewhere
> 
> Well that's still there (11.3.), spec says that if you call `BM.getReference()` prior to ABV, you get an exception.

No, I know that, I meant at some point in the long-ago past I seem to recall you couldn't even call it at `AfterDeploymentValidation` time.

**Comment by manovotn** [comment]
Oh, I see.

**Comment by ljnelson** [comment]
Ah; may have found it: https://issues.redhat.com/browse/CDI-392

**Comment by ljnelson** [comment]
Not _quite_ the right issue but in the general vicinity.  Too lazy to dig further. 😄

**Comment by manovotn** [comment]
This issue is long overdue but still valid for CDI 4.0 - https://jakarta.ee/specifications/cdi/4.0/jakarta-cdi-spec-4.0.html#after_deployment_validation
Will add it to the tracking issue for next version, see https://github.com/jakartaee/cdi/issues/622
