### ISSUE TITLE
Method invokers

### ISSUE THREAD

**Issue by arjantijms** [jakartaee/cdi#460]
(copied from CDI.Next doc, as there was no issue yet to track this)

Currently CDI does not have a concept of a bean method that can be executed from another bean with parameter binding.
Such a concept is used in other specs, such as JAX-RS, where resource methods are executed at runtime with the need to bind their parameters, and provide the support for interceptors and other CDI features.
The CDI spec should add API for such a feature, so other specs do not need to define a custom solution.

The following should be possible:

- Obtain a reference to executable method with all metadata, including annotations on method and on fields
- Execute an executable method on a bean instance
- Obtain executable method metadata in interceptors (to analyze annotations using reflection-less approach)
- Create a parameter binder, that would support a specific annotation on a parameter (basically a parameter qualifier)

Pseudocode:

Let’s consider the following bean:
```java
@RequestScoped
@Path("/greet")
public class Resource {
   @GET
   String helloWorld(@HeaderParam("HEADER") String header) {
   }
}
```

```java
@Qualifier
@Target(ElementType.PARAMETER)
public @interface HeaderParam {
   String value();
}
```

Now we could create a parameter binder:

```java
@Singleton
@Binder(HeaderParam.class)
public class HeaderParamBinder implements ParamBinder {
   // HttpHeaders is a request scoped bean
   private final HttpHeaders headers;
   private final Converter converter;

   @Inject
   HeaderParamBinder(HttpHeaders headers, Converter converter) {
       this.headers = headers;
       this.converter = converter;
   }

   public <T> T bind(HeaderParam annotation, GenericType<T> type) {
       return converter.convert(headers.getRequestHeader(annotation.value()), type);
   }
}
```

And the execution of this method would be something like:

```java
@MethodHandler(Path.class)
public class JaxRsExecutor implements ExecMethodHandler<Object, Object> {
   private final ParameterBinder binder;
   private final Container container;
  
   @Inject
   JaxRsExecutor(ArgumentBinder binder) {
       this.binder = binder;
   }

   @Override
   public void processMethod(ExecutableMethod<Object, Object> method) {
       // process registration with web server
   }
  
   private void executeMethod(ExecutableMethod<Object, Object> method) {
       // start request scope
       Object beanInstance = container.select(method.getDeclaringType()).get();
       method.invoke(beanInstance, binder.bind(method));
   }
}
```

**Comment by graemerocher** [comment]
Perhaps inspiration can be taken from Micronaut here as an implementation of this proposal effectively exists there already:

* `ExecutableMethod` - https://github.com/micronaut-projects/micronaut-core/blob/8ca3bd9569cbd94d085f966fe85817372355d09a/inject/src/main/java/io/micronaut/inject/ExecutableMethod.java
* `ExecutableMethodProcessor` - https://github.com/micronaut-projects/micronaut-core/blob/8ca3bd9569cbd94d085f966fe85817372355d09a/inject/src/main/java/io/micronaut/context/processor/ExecutableMethodProcessor.java
* `ExecutableBinder` - https://github.com/micronaut-projects/micronaut-core/blob/8ca3bd9569cbd94d085f966fe85817372355d09a/core/src/main/java/io/micronaut/core/bind/ExecutableBinder.java
* `ArgumentBinder` - https://github.com/micronaut-projects/micronaut-core/blob/8ca3bd9569cbd94d085f966fe85817372355d09a/core/src/main/java/io/micronaut/core/bind/ArgumentBinder.java

**Comment by Ladicek** [comment]
When we get to it, I believe it would be great if this API supported providing an initial context data map for eventual interceptors (`InvocationContext.getContextData()`).

**Comment by Ladicek** [comment]
I just submitted an initial proposal for this: #639.

**Comment by manovotn** [comment]
The initial proposal was merged and will be part of the first Alpha for 4.1.
However, there are still `TODOs` in the code that need addressing and until then, this issue should stay open.

**Comment by Ladicek** [comment]
The specification and TCK for this are done.

We ended up removing transformers and wrappers from CDI 4.1, those should get specified in a future version, but the main functionality is there.
