### ISSUE TITLE
Lite/Full split: does CDI in Java SE environment (SeContainer etc.) have to support Full?

### ISSUE THREAD

**Issue by Ladicek** [jakartaee/cdi#488]
I added a TODO "are implementations required to support Full?" into the CDI SE chapter, because I think this should be spelled out explicitly. The answer is probably yes, but we may need to debate it a little (because I think Micronaut is trying to implement some parts of the SE API, and I don't see anything particularly wrong with that, even though they won't support Full).

Could you please confirm whether you intend to implement `SeContainer` etc., @graemerocher?

https://github.com/eclipse-ee4j/cdi/blob/864e1b4f779e4d6d5a80f147d975a510446d4987/spec/src/main/asciidoc/javase/javase.asciidoc

**Comment by manovotn** [comment]
Is this a copy of https://github.com/eclipse-ee4j/cdi/issues/530? Cc @starksm64 

Personally I think that SE should be considered to be on top of CDI Full so I agree we should explicitly mention it
