### ISSUE TITLE
write down the rules for interceptors in CDI Lite

### ISSUE THREAD

**Issue by Ladicek** [jakartaee/cdi#545]
We verbally agreed that we want to narrow down how interceptors may be declared and bound in CDI Lite. We need to write it down to the spec.

A big part of the discussion happened in this issue: https://github.com/eclipse-ee4j/cdi-tck/issues/262 I'm copying the table that we agreed upon:

:heavy_check_mark: means "part of CDI Lite"
:x: means "not part of CDI Lite, only CDI Full"
:grey_question: means "I don't know, please help" :-)
:biohazard: means "can't happen"

| | `@AroundConstruct` | `@PostConstruct`, `@PreDestroy` | `@AroundInvoke` |
| --- | --- | --- | --- |
| On target class | :biohazard: | :heavy_check_mark: | :grey_question: |
| On interceptor class, binding annotation + `@Priority` | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark:
| On interceptor class, `@Interceptors` | :x: | :x: | :x: |
| On interceptor class, enabled using `beans.xml` | :x: | :x: | :x: |
| Implementing `Interceptor` | :x: | :x: | :x: |
| Using `InterceptionFactory` | :biohazard: | :biohazard: | :x: |

I'm leaving `@AroundInvoke` on target class as :grey_question:, but all things considered, it should really be :x:.

**Comment by graemerocher** [comment]
+1 from me
