### ISSUE TITLE
Review unused imports in classes in CDI 4

### ISSUE THREAD

**Issue by hjohn** [jakartaee/cdi#600]
I'm seeing quite a lot of imports that are only used to refer to documentation while the class or interface itself is not dependent on such a class.  Examples:

`jakarta.enterprise.inject.Instance` refers to `jakarta.enterprise.util.AnnotationLiteral` but only in `@See`

`jakarta.enterprise.context.spi.Contextual` refers to `jakarta.enterprise.inject.CreationException` only in docs

`jakarta.enterprise.inject.spi` refers to `jakarta.enterprise.inject.Alternative` and `jakarta.enterprise.inject.Stereotype` only in docs

`jakarta.enterprise.inject.spi` refers to `jakarta.enterprise.context.Dependent`, `jakarta.enterprise.inject.Disposes`, `jakarta.enterprise.event.Observes` and `jakarta.enterprise.inject.Produces` only in docs.

Is this intended? I personally consider this bad form and convert those to fully qualified names to avoid creating the illusion of dependencies on other parts of the system where there are none.

Note that if I remove those imports, a minimal set of classes (`Contextual`, `CreationalContext`, `Instance`, `Annotated`, `Bean`, `BeanAttributes`, `InjectionPoint`, `TypeLiteral`) could be extracted to support minimal implementations of this specification.

**Comment by Ladicek** [comment]
I do think this is intended, because it affects how the javadoc is rendered, but I haven't been here since the beginning, so it's just my guess :-)

**Comment by manovotn** [comment]
I vaguely recall that this was discussed in meetings before CDI 2.0 and deliberately kept this way but OFC I am not 100% sure.

**Comment by Emily-Jiang** [comment]
If the javadoc uses the full name, the import statement on the top can be omitted. It is better not to directly mention the import statement as it plays a part in the build.

**Comment by manovotn** [comment]
Let's include this in the list of issues for future version, see https://github.com/jakartaee/cdi/issues/622
@hjohn if you'd like to send a PR, that would be awesome :)

**Comment by Ladicek** [comment]
I'd repurpose this to: we need to have a proper linter in the CDI project (and the TCK).

**Comment by starksm64** [comment]
Checkstyle is what is commonly used, and the MicroProfile project has an example usage to review:
https://github.com/eclipse/microprofile-parent/blob/master/pom.xml

**Comment by manovotn** [comment]
> Checkstyle is what is commonly used, and the MicroProfile project has an example usage to review: https://github.com/eclipse/microprofile-parent/blob/master/pom.xml

I'd personally lean towards using `formatter-maven-plugin` along with `impsort-maven-plugin` as that does the formatting for any contributor the moment they run a build.
Obviously that also needs a set of rules which we'd have to take from somewhere or construct for ourselves.

**Comment by Emily-Jiang** [comment]
+1 on creating a set of rules.
