### ISSUE TITLE
Dependency on outdated JTA API

### ISSUE THREAD

**Issue by manovotn** [jakartaee/cdi#608]
The latest release of CDI 4 has a dependency on `jakarta.transaction-api` in version `2.0.0`.
That artifact is actually not Jakarta EE 10 (there is no such artifact as of now it seems?) and it in turn depends on CDI 3.0, see [this POM](https://github.com/jakartaee/transactions/blob/2.0.0/api/pom.xml#L280-L284).
The dependency is not even `optional`.

This causes a cyclic dependency that has been mentioned in the jakarta-platform mailing list - [link to the archive](https://www.eclipse.org/lists/jakartaee-platform-dev/msg03409.html). This is nothing new and the dep has existed prior to our release.

As far as I can tell, we could completely remove the JTA API dependency as it is only used in javadoc inside `TransactionPhase` enum.
Granted, the javadoc won't be as nice but we'll get rid of the dep altogether. OTOH, JTA certainly cannot remove dep on CDI API, so we are the only ones who can break that cycle.

So we have two choices:
* Remove the dependency
* Upgrade the dependency (once there is EE 10 version)

Personally, I think we can easily remove the dependency.

Either way, we should then have an SP release and I am not sure what would that take- cc @starksm64.

**Comment by Ladicek** [comment]
+1 to remove.

**Comment by manovotn** [comment]
@starksm64 I agree and I have sent a PR where I changed the `{@link }` notation to `{@code }` at which point we can remove the dependency. But I do intend to keep that open until the meeting tomorrow.

**Comment by manovotn** [comment]
In the meeting it was agreed that we would also want to remove EJB dependency and rewrite any code links to just `{@code }`.
I will update the PR accordingly today or later tomorrow.

**Comment by starksm64** [comment]
Sorry, I already merged the JTA PR. Add a new one for EJB removal.

**Comment by manovotn** [comment]
I was away from PC yesterday and didn't get to it earlier.
Here it is https://github.com/jakartaee/cdi/pull/612
