### ISSUE TITLE
Add API and/or injection capabilities to obtain "otherwise injected" bean from producer

### ISSUE THREAD

**Issue by arjantijms** [jakartaee/cdi#611]
For a producer, which is an enabled alternative, with type X it's sometimes needed to obtain the bean of type X that would have been injected for X had the producer not been there. This is in particularly the case when custom interception is being applied (though this is definitely not the only use case):

For example, a producer:

```java

@Alternative
@Priority(500)
@ApplicationScoped
public class SurroundingBean {

    @Produces
    public X produce(InterceptionFactory<X> interceptionFactory, BeanManager beanManager) {
        return ...
    }
}
```

This would obtain that "previous instance" of X via code like:

```java
X previous  =
    createRef(
        beanManager.resolve(
            beanManager.getBeans(X.class)
                       .stream()
                       .filter(e -> !e.getBeanClass().equals(SurroundingBean.class))
                       .collect(toSet())), 
            beanManager);
```

With createRef being defined as:

```java
X createRef(Bean<?> bean, BeanManager beanManager) {
    return (X) 
        beanManager.getReference(
            bean, 
            X.class, 
            beanManager.createCreationalContext(bean));
}
```

This is a lot of ceremony obviously, which could be greatly simplified.

**Comment by manovotn** [comment]
> For a producer with type X it's sometimes needed to obtain the bean of type X that would have been injected for X had the producer not been there.

I might be missing something but this doesn't really make sense to me.
Had there been another been of type `X` (with no explicit qualifiers since that's what your code shows), then with producer method in place, you now have `AmbiguousResolutionException`.

Did you perhaps mean to say that the producer is an enabled alternative?

**Comment by arjantijms** [comment]
> Did you perhaps mean to say that the producer is an enabled alternative?

Yes, sorry, I'll update the code.

**Comment by arjantijms** [comment]
> with no explicit qualifiers since that's what your code shows

To keep the example simple, of course the full lookup criteria is Type + Qualifiers.

**Comment by arjantijms** [comment]
Btw, a full working example (though in javax.*, still need to update it) can be found here: 

https://github.com/javaee-samples/javaee8-samples/blob/master/security/dynamic-rememberme/src/main/java/org/javaee8/security/dynamic/rememberme/ApplicationInit.java

I'll create a more self-contained and jakarta.* version of this soon.

**Comment by mkouba** [comment]
I don't think you should use the `BeanManager#getReference()` here; the programmatic lookup via `Instance` is IMO a more appropriate way...

**Comment by arjantijms** [comment]
> And I think we should keep it that way because it is very much a corner case.

Why is it a corner case?

> they deliberately replace the original bean during typesafe resolution

At the same time we have a dynamic interceptor API that lets one add dynamic interceptors to a type. 

> giving users an easy way to bypass this feels like saying alternatives are not worth much.

It's not bypassing it, is it? It's providing an alternative that's based on the original bean, so we can dynamically add an interceptor.

**Comment by arjantijms** [comment]
@mkouba why do you think this is a corner case? In Jakarta Security this is used quite a bit to add capabilities to the build-in authentication mechanisms (which are cdi beans).

**Comment by mkouba** [comment]
> @mkouba why do you think this is a corner case? In Jakarta Security this is used quite a bit to add capabilities to the build-in authentication mechanisms (which are cdi beans).

It's a corner case because you're trying to get around the type-safe resolution rules in a way that you filter out the producer declared on `SurroundingBean` first and then apply the ambiguous dependency resolution rules. In other words, it's not like `@Inject X` or `@Inject Instance<X>`.

**Comment by arjantijms** [comment]
Filtering is the path taken to achieve the goal; which is providing an alternative based on the original bean. 

Specifically, providing a wrapper around the bean.

Wrapping is hardly a corner case is it?

**Comment by mkouba** [comment]
> Wrapping is hardly a corner case is it?

I think it is. The original bean should not be _"injectable"_. That's how alternatives work. So you're trying to get around this rule.

**Comment by arjantijms** [comment]
> I think it is. The original bean should not be "injectable". That's how alternatives work. So you're trying to get around this rule.

What about decorators then? Don't they also inject the original bean?

```java
@Decorator
public abstract class CoderDecorator implements Coder {
    
    @Inject
    @Delegate
    @Any
    Coder coder;
````

The end-goal here is the ability to provide a custom wrapper to an existing bean with, for instance, interceptors applied.

You can't do this with plain decorators as far as I know. The custom wrapper can surely not be applied (the CDI runtime controls that via a proxy), though in all fairness I have to test whether interceptors can be applied to the decorator.

**Comment by arjantijms** [comment]
@mkouba btw, when the same issue was created here, nobody talked about it being an corner case:

https://issues.redhat.com/browse/CDI-723

There's some serieus discussion going on, multiple usages are mentioned, etc. 

But now that the issue is re-created on GitHub the immediate reaction is "no, can't do, corner case".

I wonder, can you explain that difference?

**Comment by arjantijms** [comment]
@manovotn same question to you. You created https://issues.redhat.com/browse/CDI-723 (after me asking for it on the list), but when I recreate the issue here you say it's a corner case. What changed?

**Comment by mkouba** [comment]
> What about decorators then? Don't they also inject the original bean?

That is a special case - a delegate injection point is well-defined. And yes, decorators represent an idiomatic way in CDI.

**Comment by arjantijms** [comment]
@mkouba 
> And yes, decorators represent an idiomatic way in CDI.

How do we apply interceptors to a decorator, or, alternatively, to the delegated instance?

An `InterceptionFactory` currently has the following in its definition:

```
The container must also provide a built-in bean with scope {@link Dependent}, bean type {@link InterceptionFactory} and qualifier {@link Default} that can be injected in a producer method parameter.
```

So another way of almost achieving the same goal is to have the `InterceptionFactory` injectable into a decorator.

Thoughts?

**Comment by mkouba** [comment]
You can't mix decorators and interceptors. 

> How do we apply interceptors to a decorator, or, alternatively, to the delegated instance?

This is not the goal of a decorator. Decorators are meant to implement the business logic and not to implement the cross-cutting concerns.

> So another way of almost achieving the same goal is to have the InterceptionFactory injectable into a decorator.

-1 
Again, that's not a goal of a decorator.

**Comment by manovotn** [comment]
> It's not bypassing it, is it? It's providing an alternative that's based on the original bean, so we can dynamically add an interceptor.

You are literally cutting off some bean definitions to workaround typesafe resolution which would otherwise result in the alternative being picked (`beanManager.resolve()`). That's bypassing in my dictionary :)
And it's fine if you absolutely must, but definitely not a standard usage.

> What about decorators then? Don't they also inject the original bean?

I don't see the similarity between the two cases, they seem disparate enough.

> (after me asking for it on the list), but when I recreate the issue here you say it's a corner case. What changed?

A lot of water has flown by in rivers since 2018 and I have changed my opinion in this regard. Just because there was an issue to keep track of it doesn't mean I would support it still.

> btw, when the same issue was created here, nobody talked about it being a corner case:

It didn't get any traction either hinting at it not being a common problem for more users (yes, I am aware it's not indicative but nor is your argument).
Also, the original issue doesn't mention that there is actually way to achieve this and it is not that complex after all.

**Comment by manovotn** [comment]
> But now that the issue is re-created on GitHub the immediate reaction is "no, can't do, corner case".

Well, me and Martin are not the only people on this project, you might convince other committers that it's common enough to justify the API :-)
Speaking for myself, I am just giving you my opinion on the matter.

**Comment by arjantijms** [comment]
> -1
> Again, that's not a goal of a decorator.

Then how do we apply interceptors dynamically to a (build-in) bean? 

I'm having a hard time understanding why you are so against this, where you weren't before. I mean, I understand there's now Quarkus and that interception is less wanted there (hence the new comment in the InterceptionFactory), but there's still things like GlassFish, OpenLiberty, Soteria, and Mojarra etc outside Quarkus and Cdi lite.

Jakarta Security provides build-in beans, and it's often needed to dynamically apply interceptors to those beans. We're planning to make more internal artefacts in Faces build-in beans as well, and those would then need to have the ability to have interceptors applied to them as well.

If both producers and decorators are ideology not suited for that according to you, what mechanism or artefact would be suitable?

**Comment by arjantijms** [comment]
> You are literally cutting off some bean definitions to workaround typesafe resolution which would otherwise result in the alternative being picked (beanManager.resolve()). That's bypassing in my dictionary :)

No, I'm not ;)

if you look carefully, it's still the alternative bean that's being picked and created. But this alternative bean uses things from the original bean.

> Also, the original issue doesn't mention that there is actually way to achieve this and it is not that complex after all.

Actually it does. The issue refers to:

```java
HttpAuthenticationMechanism mechanism =
    createRef(
        beanManager.resolve(
            beanManager.getBeans(HttpAuthenticationMechanism.class)
                       .stream()
                       .filter(e ->
!e.getBeanClass().equals(ApplicationInit.class))
                       .collect(toSet())),
            beanManager);
```


And:

```java
HttpAuthenticationMechanism createRef(Bean<?> bean, BeanManager
beanManager) {
    return (HttpAuthenticationMechanism)
        beanManager.getReference(
            bean,
            HttpAuthenticationMechanism.class,
            beanManager.createCreationalContext(bean));
}
```

Which is almost the exact same code presented here. Just `HttpAuthenticationMechanism.class` replaced by `X.class`.

**Comment by arjantijms** [comment]
> I don't see the similarity between the two cases, they seem disparate enough.

At a high level they are actually more similar than they look.

You produce a new bean that delegates parts or everything to another bean with the same type.

Using the producer with a delegation to the original bean, you are in full control of the exact implementation of the wrapper, as long as it adhered to the type being created.

Using the decorator with a delegation to the original bean, the wrapper is created for you.

Where they differ is in obtaining the original bean and the ability to apply interceptors.  With the decorator, obtaining the original bean is trivial, but obtaining the InterceptorFactory is not. Whereas with the producer, obtain the original bean is not trivial, but obtaining the InterceptorFactory is trivial.

**Comment by arjantijms** [comment]
@mkouba 
> Again, that's not a goal of a decorator.

Why not? I can still manually wrap the injected Delegate, and call that. Why wouldn't I be allowed in principal to have interceptors on those methods, if I'm supposed to be fully in control as decorator?

```java
@Decorator
public abstract class CoderDecorator implements Coder {
    
    @Inject
    @Delegate
    @Any
    Coder coder;

    public String codeString(String s, int tval) { 
        Coder wrapped = new CodeWrapper(coder);
        
        return wrapped.codeString(s, tval);
    }
}
```
     
The above code is not ideologically unsound, is it? That's a fairly common and idiomatic pattern. I've seen it thousands of times in the last decade or so in all kinds of code.

So why shouldn't we be ideologically allowed to have an interceptor on `CodeWrapper`?

**Comment by manovotn** [comment]
@arjantijms From the notes here and the call yesterday, I presume that the scenario we are solving is as follows. I might not have the class names spot on but the structure is what I try to capture here:

* There is an interface `HttpAuthenticationMechanism` defined by the security specification
* A basic ("default") implementation of a bean `HttpAuthenticationMechanism` exists and is provided by spec implementation; let's say this is `HttpAuthenticationMechanismImpl`
* Application (i.e. user) needs or may want to sometime define a different implementation (`CustomHttpAuthenticationMechanism`) that should be used instead of the basic one but they need to reuse the logic of `HttpAuthenticationMechanismImpl` in some way and hence try to obtain the original bean while providing an enabled alternative as a replacement.

If this case is close to what is the real problem, then I think a CDI-friendly solution would be to:

* Declare in the specification that there is an `interface DefaultHttpAuthenticationMechanism implements HttpAuthenticationMechanism`; this is what implementations provide
* Users that want to provide custom implementations then can inject `DefaultHttpAuthenticationMechanism` as a producer method parameter without any typesafe resolution issues and their producer can still easily be an enabled alternative for type `HttpAuthenticationMechanism`
* The implementation of `CustomHttpAuthenticationMechanism` can then set the basic impl as a delegate and replace/enrich whichever calls it needs to

Does this make sense? Am i even close to the actual problem? :)

**Comment by arjantijms** [comment]
> Does this make sense? Am i even close to the actual problem? :)

The above could be a case indeed, but the actual problem I was referring to is as follows;

1.

- There is an interface `HttpAuthenticationMechanism` defined by the security specification
- Via the `BasicAuthenticationMechanismDefinition` annotation (pretty much the only "custom" configuration we offer) a CDI extension adds a bean for this, e.g.  `BasicAuthenticationMechanism implements HttpAuthenticationMechanism`

2.

- We have a number of interceptors that provide extra security capabilities, such as `RememberMeInterceptor`, `AutoApplySessionInterceptor` and more.

Now the request is to join `RememberMeInterceptor` and the enabled bean for `HttpAuthenticationMechanism` together.

We have obviously thought of introducing more custom configuration for this, so the user can easily express this and the extension we have can do the hard work. But there's two major things against this:

1. With an open-ended set of interceptors it's not so easy to design a custom configuration that allows for this to begin with.
2. A stated goal of Jakarta Security is that we don't want to have our own configuration system and factories etc, but that plain CDI is used as much as possible.

**Comment by manovotn** [comment]
> Now the request is to join `RememberMeInterceptor` and the enabled bean for `HttpAuthenticationMechanism` together.

So, the custom implementation of `HttpAuthenticationMechanism` can have multiple interceptors on top whereas the basic one doesn't?
That's still doable with the approach I described above when you use interception factory there.

Is the purpose of custom `HttpAuthenticationMechanism` just to attach interceptors or is is it expected that it overrides some behavior as well?

**Comment by manovotn** [comment]
Another idea coming to mind is that you (as spec implementation) could have an extension monitoring any bean of `HttpAuthenticationMechanism` type and you could enrich it with appropriate interceptors via interception factory yourself. Obviously, you'd need to know which interceptors to pick so that's down to some way of configuration.

**Comment by arjantijms** [comment]
> So, the custom implementation of HttpAuthenticationMechanism can have multiple interceptors on top whereas the basic one doesn't?

In this example, there's not necessarily a custom implementation by the user. Jakarta Security provides 4 implementations at the moment as "build-in" beans.

The ask is to have an easy way for the user to say that the interceptors should be attached to the build-in bean.

Multiple of these interceptors can be stacked if the user wants that (eg login to continu, remember me, and audit). They have specification defined priorities.

**Comment by arjantijms** [comment]
@manovotn yet another idea, a little inspired by your `LiteExtensionTranslator` in Weld.

What if we had a build-in extension in CDI that reads a "user mode" extension from the bean archive, with some relaxed rules. The hurdle now for end-users is that when they create an extension for in their application, say a war archive, they have to put that extension into a separate jar, add a services file, add the jar as a dependency, etc.

Maybe we could in addition do something like this:

```java
@BeanArchiveExtension
public class RememberMeExtension {

    @Enhancement(types = HttpAuthenticationMechanism.class)
    public void addRememberMe(ClassConfig httpAuthenticationMechanism) {
        httpAuthenticationMechanism.addAnnotation(
            RememberMe.Literal.of(.config..));
    }
}
```

The presence of such user mode or bean archive extension would not change anything regarding the bean archive (it would still be scanned as it normally would, beans.xml would be normally processed etc). Only, the user would not have to create that separate jar, but just annotate any of its existing beans.

Thoughts?

**Comment by arjantijms** [comment]
> The only possible catch are the rules of what is a bean archive

That's a pretty big one and the reason I was talking about the "bean archive" extensions above.

Also, not all servers can read service files from a WAR META-INF folder right? Whereas WEB-INF/lib/some.jar is guaranteed. Or am I mistaken here?

If I remember well, that was the reason Spring had some own type for the ServletContainerInitialzer.

**Comment by manovotn** [comment]
> That's a pretty big one and the reason I was talking about the "bean archive" extensions above.

Adding a beans.xml file to the very same archive where you have an extension is way simpler than a whole new jar and dep management that goes along with it. Not to mention lots of deployments have beans.xml already and since CDI 4 will actually need to have them if they wish to retain the `all` discovery model anyway.

> Also, not all servers can read service files from a WAR META-INF folder right? Whereas WEB-INF/lib/some.jar is guaranteed. Or am I mistaken here?

I am not sure what's preventing you from doing that? Isn't this exactly how a sizeable chunk of CDI TCK is written?

**Comment by Ladicek** [comment]
> I guess that's an innovative usage of CDI in a way, and therefore there are a few small gaps here and there.

Is there a design document or something that I could read about how Security builds on CDI? I think there are some interesting use cases that CDI could support better, but I don't feel like I have a grasp on it.

**Comment by arjantijms** [comment]
> I am not sure what's preventing you from doing that? 

Well, I remember this somewhat older SO question:

https://stackoverflow.com/questions/7692497/tomcat-wont-load-my-meta-inf-services-javax-servlet-servletcontainerinitializ

Specifically see this comment about Spring which I referred to above:

> Spring Framework 3.1 provides a nice solution to packaging the jar oneself. spring-web-VERSION.jar contains a ServletContainerInitializer implementation and includes the META-INF/services/javax.servlet.ServletContainerInitializer file that instructs the container to load org.springframework.web.SpringServletContainerInitializer. The SpringServletContainerInitializer will then load any classes extending Spring's WebApplicationInitializer interface. Additionally, WebApplicationInitializer#onStartup is a simpler interface to implement than ServletContainerInitializer#onStartup.


and @janbartel saying the following a couple of years ago:

> Having said that, I think it really is a grey area in the spec how/if that's supposed to work at all. If you read the spec section 8.2 Pluggability (p. 95 for Servlet Spec 4.0), it only ever mentions SCIs in relation to jars. 
> 
> The possibility of the SCI being in WEB-INF/classes is never addressed at all. So I think jetty is (intending to be, and with the PR will be) lenient on this. You may want to raise an issue with the servlet spec to really get a proper clarification of this. Having said that, I think it really is a grey area in the spec how/if that's supposed to work at all. If you read the spec section 8.2 Pluggability (p. 95 for Servlet Spec 4.0), it only ever mentions SCIs in relation to jars. The possibility of the SCI being in WEB-INF/classes is never addressed at all. 


Servlet 8.2.4 says:

> The ServletContainerInitializer class is looked up via the jar services API. For each application, an instance of the ServletContainerInitializer is created by the container at application startup time. The framework providing an implementation of the ServletContainerInitializer MUST bundle in the META-INF/services directory of the jar file a file called jakarta.servlet.ServletContainerInitializer, as per the jar services API, that points to the implementation class of the ServletContainerInitializer.

> Isn't this exactly how a sizeable chunk of CDI TCK is written?

I was a bit surprised by that indeed. But it seems newer Tomcat versions at least do look at `*.jar!/META-INF/services and *.war/WEB-INF/classes/META-INF/services` even though it doesn't seem to be strictly guaranteed by the Servlet spec. /cc @markt-asf 

Most of the proposal was written under the assumption of extensions discovered by the SE service loader having to be in separate .jar files instead of `*.war/WEB-INF/classes/META-INF/services`.

If that's no longer the case practically speaking, then together with the new syntax for portable extensions it's probably just "good enough" for end users to use that way. The service file in META-INF is stil a bit of a gotcha as is the beans.xml, but that might all be explained.

**Comment by arjantijms** [comment]
> > I guess that's an innovative usage of CDI in a way, and therefore there are a few small gaps here and there.
> 
> Is there a design document or something that I could read about how Security builds on CDI? I think there are some interesting use cases that CDI could support better, but I don't feel like I have a grasp on it.

Essentially the spec document and Javadoc might be the first reference to look at. See https://jakarta.ee/specifications/security/2.0/jakarta-security-spec-2.0

**Comment by manovotn** [comment]
> Yes, absolutely. And if this proposal or something close to it, can't be accepted by CDI, that's what I/we will probably do.
> I guess that's an innovative usage of CDI in a way, and therefore there are a few small gaps here and there.

This scenario looks like something that could use a universal config approach. Basically what MP config does but for jakarta (I know there was a talk of such spec but I don't know what happened to it). Thing is, CDI isn't a configuration spec in itself.

I did browse the security spec doc a bit but would need to read it more if I find time for it.
We can discuss this topic some more during the next CDI meeting if you can make it; that might bring some extra clarity.
I am sure I am not seeing some of the reasons why you need configuration by code in this manner even when it seemingly puts more weight on user shoulders than just declarative config.

**Comment by arjantijms** [comment]
> Thing is, CDI isn't a configuration spec in itself.

Not for the kind of configuration MP Config is used for (key/values), but it is IMHO for the kind of configuration that tells you which beans need to be made available with which services (decorators and interceptors and such). Although I'm not a fan of referring to spring too much, they call (or called, it's been a while) this area configuration too.

> when it seemingly puts more weight on user shoulders than just declarative config.

It puts much less weight on the shoulders, since ultimately the building blocks are beans (authentication mechanisms and identity stores) and interceptors (services such as remember me). Now the user doesn't have to learn how to override or wrap things using some custom config, which may or may not allow for what the user wants.

Instead, if you know how to enable a bean (which can just by defining it and having it in the class path), you can tell which i.e. identity store to use. You can decorate or intercept these, return them from a producer, have them in an archive, create them from an extension, etc etc. It's all the standard CDI APIs. Making all these things possible and then specific them using the custom machinery of Faces took years, and required us to introduce tons of factories and config files and custom listeners etc.

**Comment by arjantijms** [comment]
@manovotn 
> I am not sure what's preventing you from doing that? Isn't this exactly how a sizeable chunk of CDI TCK is written?

p.s. see also this one; https://stackoverflow.com/questions/10776599/servletcontainerinitializer-vs-servletcontextlistener/

**Comment by arjantijms** [comment]
@mkouba 
> You can't mix decorators and interceptors.

You can't now, but we can make it work.

I can already wrap the injected Delegate, so again (you never answered this) why wouldn't I be able to attach interceptors to such a wrapped Delegate?

**Comment by arjantijms** [comment]
@manovotn
> I am not sure what's preventing you from doing that? Isn't this exactly how a sizeable chunk of CDI TCK is written?

Apparently, it's indeed the Servlet spec as I thought.

See https://eclipse.org/lists/servlet-dev/msg00479.html

**Comment by manovotn** [comment]
Interesting; it seems to be a de facto standard then, I didn't really encounter an issue with this so far.
On the contrary, I have seen many cases where users deliberately used this.

I didn't read the contemporary spec thought, not sure if anything changed (links you posted are years old, not that they would be wrong though)

**Comment by arjantijms** [comment]
> Interesting; it seems to be a de facto standard then, I didn't really encounter an issue with this so far.

It always used to be hit and miss whether it would work. Through the years some servers supported it, some not. I think I also saw some servers supporting it only when the Servlet startup had already started (which means only at that point the classes folder was added to the classpath).

Particularly GF has big issues with the 3 tests you added where you assume an extension in a wat and no beans.xml, meaning the war is not a BDA, but does need a bean manager in JNDI. Since GF (rightfully) never looked at web-inf/classes for extensions, this completely fails.

**Comment by arjantijms** [comment]
Even if CDI seems to make assumptions here that it shouldn't, the TCK testing for it makes it kinda de facto required to support extensions in wars. 

Although not 100% ideal and what same caveats, the build compatible extension in the war is just about good enough to somewhat easily add interceptors to beans from a user perspective.

Let's give this "win" away then, and let's focus on other battles.
