### ISSUE TITLE
TCK test InjectionIntoNonContextualComponentTest depends on pruned technologies

### ISSUE THREAD

**Issue by arjantijms** [jakartaee/cdi#621]
The test archive for `InjectionIntoNonContextualComponentTest` depends on Faces managed beans:

```xml
<managed-bean>
    <managed-bean-name>farm</managed-bean-name>
    <managed-bean-class>org.jboss.cdi.tck.tests.lookup.injection.non.contextual.Farm</managed-bean-class>
    <managed-bean-scope>request</managed-bean-scope>
</managed-bean>
```

And Jakarta Pages files for use with Jakarta Faces:

```
<%@ taglib uri="http://java.sun.com/jsf/html" prefix="h" %>
<%@ taglib uri="http://java.sun.com/jsf/core" prefix="f" %>
<html>
 <head>
  <title>Managed Bean Test Page</title>
 </head>
```

Support for these have been pruned in Faces 4. So an EE 10 runtime (with Faces 4 present) cannot pass the TCK.

cc @scottmarlow @starksm64

**Comment by starksm64** [comment]
So I have a proposed fix you could try:
https://github.com/jakartaee/cdi-tck/pull/374

Alternatively, we could just add this test to the current excluded list in the test suite. To discuss in the call tomorrow.

**Comment by starksm64** [comment]
org.jboss.cdi.tck.tests.lookup.el.integration.IntegrationWithUnifiedELTest#testELResolverRegisteredWithJsf is another test using jsf tags in a jsp file that has been updated to xhtml in the https://github.com/jakartaee/cdi-tck/pull/374 PR.

**Comment by breakponchito** [comment]
Should we need to use the 4.0.2 instead of 4.0.1?
