### ISSUE TITLE
List of potential changes/features for next CDI version

### ISSUE THREAD

**Issue by manovotn** [jakartaee/cdi#622]
This issue aims to capture ideas for next CDI version and should help us get a measure of changes we are looking at.
Eventually, this will lead to a formulation of a release plan.

**Not all issues captured here need to necessarily end up being implemented**.
They are a poll of requests and ideas that will be further discussed.
This list does *not* include TCK challenges as those are treated individually.

Please add your ideas as comments to this issue and any of the committers can then edit this comment to include it in the list.
Each suggestion should have its own tracking issue which we link here or we should at least mention that it's not being tracked so that it doesn't get forgotten.
I've also create a dedicated label `CDI.next` that we can use to mark all relevant issues.

Current known issues, ideas and suggestions:
* Correct the behavior of manually setting `CDIProvider` to correctly throw an error on repeated assignment 
  * https://github.com/jakartaee/cdi/issues/618
* Separate EL-related methods from `BeanManager` so that we can drop the EL dependency from CDI API
  * https://github.com/jakartaee/cdi/issues/613 
* Standardize a way to get hold of interceptor bindings from within an interceptor
  * https://github.com/jakartaee/cdi/issues/592
* Ability to declare `@Priority` on producers
  * https://github.com/jakartaee/cdi/issues/556
* ~~Definition of context propagation in CDI~~
  * ~~https://github.com/jakartaee/cdi/issues/474~~
  * This topic has been discussed repeatedly in meeting and numerous problems were identified; it is hence not a good candidate for next version
  * See [this ](https://github.com/jakartaee/cdi/issues/474#issuecomment-1252465508 )and [this ](https://github.com/jakartaee/cdi/issues/474#issuecomment-1252554813 )comment for a nice summary of these issues
* Proposal for executable methods
  * https://github.com/jakartaee/cdi/issues/460
* Accessing custom context instances in CDI Lite
  * https://github.com/jakartaee/cdi/issues/628 
* Review unused imports in CDI 4.0
  * https://github.com/jakartaee/cdi/issues/600
* Remove JBoss references from source files
  * https://github.com/jakartaee/cdi/issues/625
* Correct spec wording WRT `AfterDeploymentValidation`
  * https://github.com/jakartaee/cdi/issues/454
* Programmatic access to Assignability rules 
  * https://github.com/jakartaee/cdi/issues/498
* Look into applying decorators to synth beans
  * https://github.com/jakartaee/cdi/issues/459 
* Validate that observer methods have return type `void`
  * https://github.com/jakartaee/cdi/issues/636

**Comment by Emily-Jiang** [comment]
I would like the next version to address CDI context propagation
https://github.com/jakartaee/cdi/issues/474

**Comment by arjantijms** [comment]
I'd like to propose https://github.com/jakartaee/cdi/issues/459 as well for CDI.Next.

**Comment by manovotn** [comment]
Added https://github.com/jakartaee/cdi/issues/636 into the list

**Comment by Ladicek** [comment]
We'll use the [CDI 4.1/5.0 milestone](https://github.com/jakartaee/cdi/milestone/1) for defining the next CDI version. For now, I added all issues listed here to that milestone, but that doesn't express commitment. I'll keep this issue open so that non-committers can provide feedback. I'll remove the _CDI.next_ label, which is cumbersome to work with.

**Comment by manovotn** [comment]
I'll close this issue as we are now actively using GH milestone to track all related issues.
Folks can still use related issues to provide their feedback or create a new one.
