### ISSUE TITLE
How is ContainerLifeCycleEventRuntimeInvocationTest.testAfterBeanDiscoveryEventFails supposed to pass?

### ISSUE THREAD

**Issue by arjantijms** [jakartaee/cdi#624]
The CDI TCK test `org.jboss.cdi.tck.tests.extensions.lifecycle.events.ContainerLifeCycleEventRuntimeInvocationTest.testAfterBeanDiscoveryEventFails()` uses an extension that stores an `AfterBeanDiscovery` event:

```java
public class TestExtension implements Extension {

    private AfterBeanDiscovery abd;

    void observesAfterBeanDiscovery(@Observes AfterBeanDiscovery event) {
        this.abd = event;
    }

    public AfterBeanDiscovery getAfterBeanDiscovery() {
        return abd;
    }
}
```

The test then make a call to this stored event later, which is supposed to throw an `IllegalStateException`

```java
AfterBeanDiscovery event = extension.getAfterBeanDiscovery();

     new Invocation() {
            void execute() {
                event.addBean();
            }
      }.run();
```

In Weld this throws a NullPointerException, since a `postNotify` calls sets a `receiver` to null:

```java
public abstract class ContainerEvent implements NotificationListener {

    private Extension receiver;

    @Override
    public void preNotify(Extension extension) {
        this.receiver = extension;
    }

    @Override
    public void postNotify(Extension extension) {
        this.receiver = null;
    }
```

And the `addBean()` from the test uses this receiver and doesn't assume it's null:

```java
@Override
    public <T> WeldBeanConfigurator<T> addBean() {
        return addBean(getReceiver().getClass());
    }
```

This all happens internally in Weld, without seemingly any option for an integrator to come between this or to influence this.

What is an integrator supposed to do here?

cc: @starksm64 @manovotn

**Comment by starksm64** [comment]
This is a bug that crept in recently that @manovotn fixed in this PR:
https://github.com/weld/core/pull/2746

There will have to be a new Weld release for this.

**Comment by arjantijms** [comment]
Oh wow, thanks for the reference. Isn't the CDI TCK executed for every Weld release?

**Comment by manovotn** [comment]
> Oh wow, thanks for the reference. Isn't the CDI TCK executed for every Weld release?

It is in embedded and with WFLY. However, in WFLY I wasn't able to execute several tests (this one included) due to issues with other related EE 10 technologies. And this test isn't triggered in embedded mode so it slipped past.
I am just working towards having full WFLY run for each weld PR again so that this situation won't repeat :)
