### ISSUE TITLE
Remove the JBoss reference from copyright and license headers

### ISSUE THREAD

**Issue by waynebeaton** [jakartaee/cdi#625]
Many of the source files include this text at the very top of the file, as part of the copyright and license header:

> JBoss, Home of Professional Open Source

Please remove it.

Some time shortly after the next release would be good timing.

**Comment by starksm64** [comment]
OK, but could you explain why this is being requested? That header file has been in place since the project inception.

**Comment by waynebeaton** [comment]
1. Jakarta CDI is an Eclipse/Jakarta EE project, not a JBoss Project.
2. The statement is effectively an advertisement for a specific vendor.
3. It is suggestive of a particular implementation of the specification being more special than other implementations.
4. There's no technical or legal reason for it to be there.

If you're wondering "why now?"... I only just noticed it. It never occurred to us before now to look for this sort of thing when we do IP checks.

**Comment by manovotn** [comment]
I've linked this to the list of future version issues as it seems nobody is keen on sacrificing their time to it now.

**Comment by waynebeaton** [comment]
````
$ find . -type f -print0 | xargs -0 sed -E -i "/^ \* JBoss, Home of Professional Open Source$/d"
$ find . -type f -print0 | xargs -0 sed -E -i "/^~ JBoss, Home of Professional Open Source$/d"
$_
````

There are two files that appear to have managed headers. My best guess is that some automated formatting was applied. We _could_ `sed` these, but I'm thinking that some manual reformatting is probably preferred.

- ./api/src/main/resources/beans_1_0.xsd
- ./api/src/main/resources/beans_1_1.xsd

Shall I submit a pull request?

**Comment by manovotn** [comment]
> Shall I submit a pull request?

@waynebeaton a friendly reminder in case you find a chunk of time to send that PR :)

**Comment by Ladicek** [comment]
We should probably have a linter for license headers.

**Comment by waynebeaton** [comment]
Pull request has been delivered.

I ran the build and the tests all pass.

I hesitated to change the XSD files, but mostly because I don't really understand how they're disseminated and the impact of a non-functional change. Is there any reason why we shouldn't change these files?

**Comment by manovotn** [comment]
> I hesitated to change the XSD files, but mostly because I don't really understand how they're disseminated and the impact of a non-functional change. Is there any reason why we shouldn't change these files?

Do you mean beans.xsd files? I only see this vendor line in the two oldest one BTW. And I don't know why changing them would be an issue.
