### ISSUE TITLE
Accessing custom context objects in CDI Lite

### ISSUE THREAD

**Issue by JHahnHRO** [jakartaee/cdi#628]
If a build compatible extension adds a custom scope via `MetaAnnotations#addScope`, there will be exactly one context object of the given context class in the container if I read the JavaDoc correctly. However, there seems to be no way to extract this unique instance from the container once its running, except via `BeanContainer#getContext` and that only works if the context object I want is immediately active after instantiation and also happens to be the unique active context object for its scope.

This makes it surprisingly hard to define a new scope and context that can be programmatically activated and deactivated, like the RequestScope can.

In CDI full, this would be easy with a portable extension, because then I actually add the context objects themselves, not just a context class, and I could just store them in some field in the Extension and extract them later by injecting the Extension somewhere. In CDI Lite however, I would have to do a non-zero amount of shenanigans, e.g. 

- I could make the constructor store a reference to the new instance in some static variable somewhere and hope nobody except the container will ever ever ever call that constructor. This introduces fragile global state and makes it impossible to have multiple containers running in parallel (for unit testing say).
- Or I could have the context active immediately after instantiation, call `getContext(MyScope.class)` and store the object in some `@Singleton` bean by listening to a start up event and then immediately deactivate the context until it is truly needed. It is probably semantically wrong to have to scope start out as active if the scope should be programmatically activated and deactivated. Also, this is simply impossible if I ever need to context classes for the same scope. Deactivating the context may accidentally trigger `@MyScope` scoped beans that listen to a `@BeforeDestroyed` event.

It's probably possible to find better workarounds with even more shenanigans, but that seems unnecessarily hard. Has this simply been overlooked or is it by design not (easily) possible in CDI Lite?

**Comment by manovotn** [comment]
> and I could just store them in some field in the Extension and extract them later by injecting the Extension somewhere

This is one of the main reasons why we cannot use standard extensions in Lite. The state is not portable between build and runtime (not for all environments at least).

I guess this is why Quarkus has [this method](https://github.com/quarkusio/quarkus/blob/main/independent-projects/arc/runtime/src/main/java/io/quarkus/arc/ArcContainer.java#L32-L37) but it didn't occur to me when we designed this API. Maybe we should add something similar to the `BeanContainer`, it should work for Full as well. WDYT @Ladicek?

**Comment by Ladicek** [comment]
I agree we forgot to make the context objects easily available at runtime, and we should add a method to `BeanContainer` for that. Something like this:

```java
/**
 * Obtains all {@linkplain Context context objects}, active and inactive, for the given
 * {@linkplain jakarta.enterprise.context scope}.
 *
 * @param scopeType the {@linkplain jakarta.enterprise.context scope}; must not be {@code null}
 * @return immutable collection of {@linkplain Context context objects}; never {@code null}, but may be empty
 */
Collection<Context> getContexts(Class<? extends Annotation> scopeType);
```

**Comment by Ladicek** [comment]
Just thinking about the use case here, an alternative solution could be:

```java
/**
 * Obtains the {@linkplain Context context object} of given class for given
 * {@linkplain jakarta.enterprise.context scope}. If no context object whose class
 * is equal to {@code contextClass} exists for given scope, returns {@code null}.
 *
 * @param scopeType the {@linkplain jakarta.enterprise.context scope}; must not be {@code null}
 * @param contextClass the class of desired context object; must not be {@code null}
 * @return the {@linkplain Context context object}, or {@code null} if no such context object exists
 */
Context getContext(Class<? extends Annotation> scopeType, Class<? extends Context> contextClass);
```

This is probably more user-friendly, but less general, so I think I'm leaning towards the previous suggestion. Just wanted to mention the option.

**Comment by manovotn** [comment]
The first one (same as Arc has) is better because you can have several impls of any given context, all of which are for same scope annotation and can have same "base" context class. In such case the second option is ambiguous in what it returns.

**Comment by manovotn** [comment]
> Would a hypothetical `getContexts(Class<? extends Annotation>)` method return active and inactive contexts? Or just active ones (which is what `getContext(Class<? extends Annotation>)` currently does, bearing in mind of course that contexts may become active or inactive at any point for any reason, so the existing `getContext(Class<? extends Annotation>)` contract represents only a "best effort")?

It would return all, active or not, otherwise it doesn't solve the issue presented here. 
The problem is that you have no way to get hold of the instance of your custom context that CDI uses, especially if it is not active or of you have more than one impl for given scope (such as, for instance, Weld uses several contexts for `RequestScoped`)

**Comment by Ladicek** [comment]
The javadoc in my `getContexts` proposal above directly says "all context objects, active and inactive, for the given scope".
