### ISSUE TITLE
Wrong maven coordinate on the CDI 4.0 spec page

### ISSUE THREAD

**Issue by bstansberry** [jakartaee/cdi#631]
There's a typo on https://jakarta.ee/specifications/cdi/4.0/

The "Maven coordinates" link reads 'jakarta.enterprise:jakarta.cdi-api:jar:4.0.1' (missing ".enterprise" in the artifactId).

The link URL is ok; it's just a problem in the link text.

**Comment by manovotn** [comment]
@starksm64 I can see you have a commit fixing this on a fork but no PR; probably an oversight?

**Comment by starksm64** [comment]
I forgot which branch/repo I was using for the core profile specification. That ballot closed yesterday, so if this just gets fixed in the merge I'll close this, otherwise I'll revert it and do a fix branch.

**Comment by starksm64** [comment]
This has been corrected.
