### ISSUE TITLE
LICENSE-2.1-SNAPSHOT reference, missing license

### ISSUE THREAD

**Issue by bodorjzsolt** [jakartaee/cdi#632]
The file SecurityActions.java - and maybe other files also- contain a license reference with a link to http://www.apache.org/licenses/LICENSE-2.1-SNAPSHOT . The link is not working, the text is very similar with an Apache 2.0 reference but is this a new apache license? I's a bit confusing.

**Comment by manovotn** [comment]
This is already contained in #625 (meaning it will be fixed when the aforementioned issue is addressed).
I think we can close this one as #625 effectively requires removal of these headers altogether.
