### ISSUE TITLE
docs/README.md outdated

### ISSUE THREAD

**Issue by ekimike** [jakartaee/cdi#642]
Minor: The seventh step asks us to navigate to `http://localhost:4000/` but the console says `http://127.0.0.1:4000/cdi/` which actually is the one that works.  Should I update it?

**Comment by ekimike** [comment]
Do I need to do an extra thing besides configuring my ssh access in order to be able to push my local branch? Because I'm getting the following message:

```
ERROR: Permission to jakartaee/cdi.git denied to ekimike.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by pzygielo** [comment]
> Do I need to do an extra thing besides configuring my ssh access in order to be able to push my local branch? Because I'm getting the following message:
> 
> ```
> ERROR: Permission to jakartaee/cdi.git denied to ekimike.

Just to be [ee4j.cdi](https://projects.eclipse.org/projects/ee4j.cdi/who) committer. If you are not - fork the repo and push to your fork instead.

**Comment by ekimike** [comment]
> > Do I need to do an extra thing besides configuring my ssh access in order to be able to push my local branch? Because I'm getting the following message:
> > ```
> > ERROR: Permission to jakartaee/cdi.git denied to ekimike.
> > ```
> 
> Just to be [ee4j.cdi](https://projects.eclipse.org/projects/ee4j.cdi/who) committer. If you are not - fork the repo and push to your fork instead.

Thanks, it worked, I already have an [MR](https://github.com/jakartaee/cdi/pull/643) waiting for approval, it is my first time doing this here, and I'd like to know what is the next step.

**Comment by manovotn** [comment]
> Thanks, it worked, I already have an https://github.com/jakartaee/cdi/pull/643 waiting for approval, it is my first time doing this here, and I'd like to know what is the next step.

Sending a PR from your own fork is a common practice even for commiters. Next step is a review from some of the contributors (which I left there) followed by making requested changes. Once that is completed, the PR will get an approval from commiter(s) and will then get merged.
