### ISSUE TITLE
ProcessBeanAttributes order

### ISSUE THREAD

**Issue by jeanouii** [jakartaee/cdi#666]
Currently, the order defined is PIP -> PIT -> PBA -> PB (or PP).
Anyways, considering the impact of mutating Bean attributes using the PBA event, wouldn't it be better to have the PBA triggered first and before PIP/PIT?

**Comment by manovotn** [comment]
I don't think that's good idea and below are just a few thoughts from the top of my head as to why:

- PBA allows you to change things such as types, qualifiers, stereotypes, name and alternative flag.
None of the above is linked to PIT or PIP so I am not sure I see what would be the benefit of altering beans via PBA first and then doing the other events?
- While bootstrapping, CDI [Full] first works with `AnnotatedType` which it later converts into `Bean`; PIT still operates on `AnnotatedType` (`PIT#getAnnotatedType()`) while PBA is already a point at which you move onto `Bean`. Swapping them around would break this logical procedure.
- Having PIP and PIT *before* PBA actually has a use case - you are able to monitor the injection target and injection points of a given bean and after you have that information, you can still decide to either change or veto the bean.

Last but not least, this sequence is well defined (in terms of not being ambiguous) in the spec and changing it would be backwards incompatible. That's of course doable but while I can imagine cases which it breaks and that won't work afterwards (see my third point above), I don't really see what's the gain in it. Maybe I am just missing something?

**Comment by manovotn** [comment]
Agreed with @jeanouii on the CDI mtg that we can close this issue.
