### ISSUE TITLE
Fix enabled beans link in CDI Full

### ISSUE THREAD

**Issue by jeanouii** [jakartaee/cdi#667]
We discussed it, and I think @Ladicek fixed it, but in case we have done, opening this issue, to make sure we do it and it appears in the release notes.

In section https://jakarta.ee/specifications/cdi/4.0/jakarta-cdi-spec-4.0.html#bean_discovery_steps_full the bullet list links to <<Enabled beans>> but the link is actually wrong because there is another section for enabled beans in CDI Full mode.

So there is a mismatch. If you strictly read and follow the link, enabled beans do not take Specialized beans into account. The TCK is currently testing them and there is a definition in the document to amend the enabled beans definition in the context of CDI Full.

**Comment by jeanouii** [comment]
I'm even wondering why there is a different rule for enabled beans in the CDI Full context to be honest.
For instance, from a user point of view, it would be easier to understand if we would always fire PBA for all beans (without all the specialization boiler plate). There won't be a PB afterward, when we have all the bean set and mutated attributes or vetoed beans.

**Comment by Ladicek** [comment]
I actually found that I only have the fix in my local checkout of the repo, I didn't submit a PR yet. Thanks for the reminder! :-)

When it comes to event ordering, I guess that would fall under #666?
