### ISSUE TITLE
Breaking up spec/TCK to remove circular dependencies

### ISSUE THREAD

**Issue by starksm64** [jakartaee/cdi#687]
A long standing issue is that we references to downstream specifications like Servlet, Transactions, etc. A summary of the issues can be found in the following Jakarta EE 11 issue:

https://dev.azure.com/jakarta-ee-azdo/jakarta-ee-azdo/_workitems/edit/98

The most correct thing is to break up the specification and TCKs into separate repos that layer the dependencies. This is something that is being done for MP-JWT to allow separation on the Jakarta dependencies.

The simplest thing todo is simply separate the TCK into finer grain artifacts that also layer the dependencies. 

The only problem with this is that ideally a TCK that describes requirements for CDI/Servlet integration would be released as part of the Serlvet specification ballot. 

Tasks for EE 11

- [ ] Extract Integration requirement to a section of the specification into a platform/profile specification
- [ ] Move web TCK test module to the platform spec
- [ ] Remove the web test module from the CDI TCK core

**Comment by Ladicek** [comment]
I would like to point out one thing: in CDI, the spec and the TCK are already broken apart. The CDI spec depends only on projects that are "below" CDI (Jakarta Annotations, Jakarta Interceptors, Jakarta Dependency Injection, Jakarta Expression Language).

Further, the CDI TCK is also broken apart: there are some supplementary modules, the CDI Lang Model TCK (which is not interesting here), and 2 main TCK modules:

- `impl`, which contains tests for Core CDI and CDI SE and only depends on projects that are "below" CDI,
- `web`, which contains tests for CDI EE and depends also on projects that are "above" CDI.

So technically, we could release CDI early and CDI TCK late. That probably breaks some rules, so another option, probably a path of least resistance, is to break out the `web` module into something like `cdi-tck-ee`. Then, CDI and CDI TCK would be released early, and CDI TCK EE would be released late. Would something like that work?

I generally agree that if CDI is truly a corner stone of Jakarta EE, then it should be the projects "above" CDI who specify how they integrate with CDI, but historically, there hasn't been a lot of enthusiasm for doing that.

**Comment by edburns** [comment]
## Scott's proposal

1. Take the current CDI spec and break it up into

   - "integration spec" this is where behaviors relative to other
     Jakarta EE specs, downstream dependencies, are specified. It is
     an integration spec because it is a spec that covers the
     integration between CDI and everything else.
     
   - "CDI implementation spec" the rest of the spec after the
     integrations have been taken out.
     
2. TCK

   - the integration spec will have its own TCK.
   
   - CDI implementation spec will have its own TCK.
   
   - There will be no shared tests between these two TCKs.

3. Jakarta EE Core profile will only reference "CDI implementation spec".

4. Jakarta EE Web and Platform will reference "integration spec" and
   "CDI implementation spec".

5. What about the POMs for the TCKs?

   Consider these.
   
   - web/pom.xml
   
      We plan to pull the `web/pom.xml` out of the CDI TCK distribution
      and put it into a new artifact associated with the "integration
      spec".

   - impl/pom.xml
   - lang-model/pom.xml
   
      These will be in the TCK for "CDI implementation spec".

6. What about the waves?
   
   "integration spec" will be in wave 7
   
   "CDI implementation spec" will be in wave 3

**Comment by starksm64** [comment]
> So technically, we could release CDI early and CDI TCK late. That probably breaks some rules, so another option, probably a path of least resistance, is to break out the `web` module into something like `cdi-tck-ee`. Then, CDI and CDI TCK would be released early, and CDI TCK EE would be released late. Would something like that work?
> 

Yes, this breaks the current IP flow of the Jakarta specification process where the voting happens on the spec and TCK. As you point out, it really should not take much work to simply break the CDI spec into a base and integration spec with attendant TCKs that would produce two clear spec/TCK bundles that follow the specification process rules.

**Comment by Ladicek** [comment]
I see. Given that I'm skeptical about other specs adopting the CDI integration concerns, I think moving the CDI EE spec out CDI itself into another specification called "CDI EE" would be easiest. On the TCK front, that basically amounts to moving the `web` module into a TCK of the new spec.

Why would I call it "CDI EE"? Because that's how it called today. The less changes, the better :-)

**Comment by starksm64** [comment]
It won't be outside of the CDI project, it will simply be another specification like dependency injection managed by the CDI specification project. A CDI EE + current web submodule of existing TCK would be the contents as you are saying.

**Comment by edburns** [comment]
Hello @starksm64 and @Ladicek. Based on this comment:

> Why would I call it "CDI EE"? Because that's how it called today. The less changes, the better :-)

Can you please confirm:

- What I called ["CDI integration spec"](#issuecomment-1644757507) will be called "Jakarta Contexts and Dependency Injection Enterprise Edition (Jakarta CDI EE)".
- What I called ["CDI implementation spec"](#issuecomment-1644757507) will be called "Jakarta  Contexts and Dependency Injection Enterprise Edition (Jakarta CDI)".

**Comment by JanWesterkamp-iJUG** [comment]
I highlighted the Platform level component spec integration tests in the current CDI TCK Web Impl above and list them here again for clarification:

- Jakarta Messaging
- Jakarta Connectors

**Comment by Emily-Jiang** [comment]
Another solution is to move the CDI EE part to either web profile or platform spec and then put the tcks in the respective repo and CDI team owns the tests. In this way, there won't be individual -ee specs, which might double the spec sizes for no apparent content addition. It will be nicer to have the umbrella spec contains the spec interactions.

**Comment by hantsy** [comment]
A little confused about the CDI EE, why not move the CDI and spec integration to the certain spec. 

* For example, Original CDI Servlet support in CDI 4.0, move it to Servlet, add a CDI support section in Servlet spec. If possible provide a new module under servlet for CDI- `jakarta.servlet.cdi`.
  Faces, Jaxrs can split the _Injection Provider SPI and implementation_, and provide default implementation by CDI, in Jakarta EE environment, the injection is enabled by CDI,  in Spring etc,(no CDI implementation in the classpath), it can be provided by Spring. 
  
  For those specs integrated CDI tightly, CDI is part of the deps.

* Thus we only have a CDI spec, can run pure Java or Jakarta EE Container, can be a direct dep for other specs(or its CDI module).

**Comment by Ladicek** [comment]
Feel free to ask the Servlet spec if they want to own the CDI integration concerns :-)

Hint: they already indicated in the past that they don't, see e.g. https://github.com/jakartaee/servlet/issues/116 or https://issues.redhat.com/browse/CDI-492

**Comment by starksm64** [comment]
@arjan tijms ***@***.***> is going to ask on the servlet dev
list. The issue in the past has been that the servlet core team was not
interested in CDI integration, and so this really is an EE platform
integration issue that should be done in a separate spec to avoid
dependency issues. For now this is happening in CDI EE. In the future it
could be a Web Profile integration spec.

**Comment by starksm64** [comment]
So the restructuring review ballot to move the integration contents into a new CDI EE spec failed the spec committee ballot due to question about whether this was a general approach all specs should take. What has been decided as the approach for EE 11 is to have integration requirements move into the corresponding platform spec or profile. A new restructuring review ballot for this change will kick off this week.

**Comment by Ladicek** [comment]
I would frankly prefer CDI EE over putting things into the platform spec, because of clear ownership. But I won't lose sleep over it :-)

**Comment by edburns** [comment]
I have incorporated the latest on this matter into the EE 11 release plan. I seek your review at https://github.com/jakartaee/platform/pull/808 @Ladicek @starksm64 .

**Comment by starksm64** [comment]
The bulk of the work on the CDI component spec project side is done with:
https://github.com/jakartaee/cdi/pull/755
https://github.com/jakartaee/cdi-tck/pull/532

There will still be work needed to complete the integration of the CDI EE requirements into the platform as part of this PR:
https://github.com/jakartaee/platform/pull/838
