### ISSUE TITLE
Build Compatible Extensions can't @Enhance classes without knowing the type in advance

### ISSUE THREAD

**Issue by Azquelt** [jakartaee/cdi#691]
Imagine I have an annotation `@DataStorage` which I want allow users to place on CDI beans.

With a portable extension, I can observe all types annotated with `@DataStorage` like this:

```java
    public void findTypes(@Observes @WithAnnotations(DataStorage.class) ProcessAnnotatedType<?> type) {
        System.out.println("Observed interface: " + type);
        dataStorageInterfaces.add(type.getAnnotatedType());
    }
```

There's no equivalent way to do this with Build Compatible Extensions because you must provide the type in the `@Enhance` annotation.

You can leave it blank, but per the definition that just means it will match no types (rather than all types)

```java
    @Enhancement(types = {}, withAnnotations = DataStorage.class)
    public void enhance(ClassInfo dataStorageClass) {
        System.out.println("BCE observed: " + dataStorageClass);
    }
```

This is potentially an issue for Jakarta Data because they're currently saying that [a Repository provider should create a bean for every interface annotated with](https://github.com/jakartaee/data/blob/c6e88adc7b76612201f3a30fae1fdead13129d96/spec/src/main/asciidoc/jakarta-ee.adoc#cdi-extension) `@Repository`.

Because `@Repository` is a bean defining annotation (per the [Repository Javadoc][repository-javadoc]), this is quite possible to do just with portable extensions, but currently not possible with build compatible extensions.

[repository-javadoc]: https://github.com/jakartaee/data/blob/c6e88adc7b76612201f3a30fae1fdead13129d96/api/src/main/java/jakarta/data/repository/Repository.java#L29-L32

**Comment by manovotn** [comment]
Couldn't you use `Object` as a type?

**Comment by Azquelt** [comment]
Huh, I'm not sure why I didn't try that. It does indeed work.

I didn't realise interfaces counted as subtypes of `Object`, but it looks like they do.

Thanks.

**Comment by Ladicek** [comment]
All reference types in Java are subtypes of `Object`, even arrays :-)
