### ISSUE TITLE
Rename master to main

### ISSUE THREAD

**Issue by edburns** [jakartaee/cdi#694]
- Request for permission to file GitLab ticket: https://www.eclipse.org/mhonarc/lists/cdi-dev/msg00779.html
- Grant of permission: https://www.eclipse.org/mhonarc/lists/cdi-dev/msg00779.html

**Comment by edburns** [comment]
Feel free to assign this to @edburns .

**Comment by edburns** [comment]
https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/3836

**Comment by Ladicek** [comment]
Any plans to also do this for https://github.com/jakartaee/cdi-tck ?
