### ISSUE TITLE
`CDI.setCDIProvider()` throwing on a repeated set is inconvenient

### ISSUE THREAD

**Issue by Ladicek** [jakartaee/cdi#695]
The `CDI.setCDIProvider()` method has been documented to throw `IllegalStateException` on repeated call since version 1.0, but since version 2.0, the implementation in fact didn't honor this documentation. Multiple implementations started to silently depend on repeated `setCDIProvider()` being allowed.

Now that we actually fixed that for 4.1 (see #619 and #690), it turns out that this is very inconvenient. I know @manovotn and @Azquelt had problems with Weld, I stumbled upon this problem with ArC today as well.

We briefly discussed this on the CDI call yesterday and there was no objection to actually making this officially allowed (it was practically allowed since CDI 2.0).

**Comment by manovotn** [comment]
> (it was practically allowed since CDI 2.0).

Just to expand, the code allowed this starting CDI 4 until and including CDI 4.
The only part forbidding it was a piece of javadoc text IIRC.

The problems I encountered were mostly related to testing and I think it was similar for @Ladicek in Arc impl.

I am also +1 to make it allowed, we just need to look through docs in case there are other mentions of this.

**Comment by Ladicek** [comment]
Good point. The only place in the specification that talks about `CDIProvider` is https://jakarta.ee/specifications/cdi/4.0/jakarta-cdi-spec-4.0.html#provider, and that doesn't mention repeatable calls of `setCDIProvider()` at all. So I believe you're correct in that the only place mentioning this is the `setCDIProvider()` method javadoc.
