### ISSUE TITLE
Release jakarta.interceptor-api 2.2

### ISSUE THREAD

**Issue by starksm64** [jakartaee/cdi#754]
Is there anything preventing doing a 2.2.0 final release of jakarta.interceptor-api?

**Comment by manovotn** [comment]
Nothing I am aware of from CDI perspective

**Comment by Ladicek** [comment]
Now that you merged https://github.com/jakartaee/interceptors/pull/106, I think we're good.

**Comment by starksm64** [comment]
This has been done.
