### ISSUE TITLE
Maybe rename `cdi-el-api` to `cdi-ee-api`? (and similar)

### ISSUE THREAD

**Issue by Ladicek** [jakartaee/cdi#777]
I had this idea recently that perhaps we should do these renames:

- `cdi-el-api` -> `cdi-ee-api`
- `jakarta.enterprise.inject.spi.el` -> `jakarta.enterprise.inject.spi.ee`
- `ELAwareBeanManager` -> `EEBeanManager`

I know it's late, but we technically still have time to do this, if we think it's for the better.

I find it fairly unlikely that we'll ever add anything to this artifact, or to the EL-aware `BeanManager`, so it's not a big deal, but the new names are a little bit more future-proof. Plus they better match the structure of the specification (even though CDI EE is no longer part of the CDI specification).

WDYT? @manovotn @Azquelt @starksm64

**Comment by Ladicek** [comment]
Discussed on the CDI call and decided not to do this.

**Comment by Emily-Jiang** [comment]
This will be a backward incompatible change. I don't think we can do this.

**Comment by Ladicek** [comment]
This _wouldn't_ be a breaking change. The `cdi-el-api` etc. are being added in CDI 4.1, so we still _could_ do this if we wanted to.
