### ISSUE TITLE
Add a beans_4_1.xsd descriptor

### ISSUE THREAD

**Issue by starksm64** [jakartaee/cdi#792]
**Is your feature request related to a problem? Please describe.**
Apparently there is now a requirement to provide a new deployment descriptor for the major/minor updates even if there is no change in content.

**Describe the solution you'd like**
Copy the beans_4_0.xsd to beans_4_1.xsd and change 4.0 to 4.1. The spec also needs to be updated.

**Comment by starksm64** [comment]
@manovotn Does this break anything in Weld if a deployment descriptor uses a 4.1 version such as:
```xml
<beans xmlns="https://jakarta.ee/xml/ns/jakartaee"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="https://jakarta.ee/xml/ns/jakartaee
         https://jakarta.ee/xml/ns/jakartaee/beans_4_1.xsd"
         version="4.1">
            ...
         </beans>
```
?

**Comment by starksm64** [comment]
I tried a basic test in the current Weld main branch and don't see any problem. I also don't see anywhere the version dictates any behavior.

**Comment by manovotn** [comment]
> @manovotn Does this break anything in Weld if a deployment descriptor uses a 4.1 version such as:
> 
> ```
> <beans xmlns="https://jakarta.ee/xml/ns/jakartaee"
>          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
>          xsi:schemaLocation="https://jakarta.ee/xml/ns/jakartaee
>          https://jakarta.ee/xml/ns/jakartaee/beans_4_1.xsd"
>          version="4.1">
>             ...
>          </beans>
> ```
> 
> ?

No, shouldn't make a difference.
